app_homepage:
    path: /
    controller: App\Controller\MainController::index

app_jeu:
    path: /jeu/{id}
    controller: App\Controller\JeuController::index

app_jeu_detail:
    path: /jeu/{id}/detail
    controller: App\Controller\JeuController::index

app_admin_jeu:
    path: /admin/jeu
    controller: App\Controller\JeuAdminController::index


    
